// <auto-generated />
namespace OmerKurtaran.WebUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _base : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_base));
        
        string IMigrationMetadata.Id
        {
            get { return "202003172311092_base"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
